services:
  backend-dev:
    volumes:
      - ./backend/:/app/
    build:
      context: ./backend
      dockerfile: Dockerfile.dev

  frontend-dev:
    depends_on:
      - backend-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app/
    environment:
      - BACKEND_URL=http://backend:8080
    ports:
      - '4200:4200'

  redis:
    container_name: redis
    image: docker.io/library/redis:alpine
    command: redis-server --save 30 1 --loglevel warning
    volumes:
      - redis-data:/data
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE

volumes:
  redis-data: